apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2022-11-02T07:27:14Z"
  name: nodeapp
  namespace: default
  resourceVersion: "18574"
  uid: ba05a8a0-3464-464f-90c5-dcf42537911c
spec:
  maxReplicas: 2
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 1
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeapp

